---
title: "Homework 4"
author: "Lizzy Gibson"
date: "October 24, 2017"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
---

```{r setup}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(tidyverse)
library(janitor)
```

## Read and Merge 538 Data
```{r}
pols <- read_csv("./fivethirtyeight_datasets/pols-month.csv") %>% 
  clean_names() %>% 
  mutate(president = ifelse(prez_gop == 0, "dem", "gop")) %>% 
  mutate(date = lubridate::floor_date(mon,"month")) %>% 
  select(-mon) %>% 
  arrange(date)

gdp <- read_csv("./fivethirtyeight_datasets/GDP.csv", na = ".") %>% 
  clean_names() %>% 
  select(date, gdp_value = value) %>% 
  mutate(date = lubridate::floor_date(date,"month"))

five38 <- inner_join(pols, gdp, by = "date") %>% 
  select(date, everything())
```

### View Data
```{r view}
five38
```

## GDP Value over Time

```{r_five38_plot}
five38 %>% 
  ggplot(aes(x = date, y = gdp_value, color = president)) + geom_point() +   
  geom_smooth(alpha = 0.1) + labs(x = "Date", y = "GDP Value", title = "Figure 2: GDP Value Over Time for Each Presidential Party")
```

From Figure 2 above, it can be seen that whether the president was a democrat or republican, the GDP increased from the 1960's to the 1980's (where it peaked) and then declined past the 2000's. Though, on average, the GDP was higher with republican presidents than democratic ones until the late 90's. 


